<?xml version="1.0" encoding="UTF-8"?>

<message xmlns="http://podaac.jpl.nasa.gov/webservice/schema" type="PRODUCT">
  <productMsg>
    <ingestMsg metadataExpanded="false">
      <project>QSCAT</project>
      <batch>0922</batch>
      <contributor>thomas.huang@jpl.nasa.gov</contributor>
      <requestedTime>1196799269735</requestedTime>
      <ingestiblePackages>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="QS_Q0A20071910154.20071910435">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q0A20071910154.20071910435</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q0A20071921557.20071921924">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q0A20071921557.20071921924</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q0A20071970022.20071970343">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q0A20071970022.20071970343</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT INVENTORY ENTRY">
          <version>0</version>
          <files count="10">
            <fileIngestible isMetadata="true" name="qscat_L0_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L0_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_L3_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L3_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_L1A_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L1A_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_L1B_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L1B_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_L2A_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L2A_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_L2B_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L2B_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_anc_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_anc_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_raw_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_raw_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_L2ACP12_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L2ACP12_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="true" name="qscat_L2BCP12_0922.lod">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/lod/qscat_L2BCP12_0922.lod</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="NRT_ICEM2007191">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/NRT_ICEM2007191</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="NRT_ICEM2007194">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/NRT_ICEM2007194</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="NRT_ICEM2007196">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/NRT_ICEM2007196</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="QS_Q1A41948.20071910319">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q1A41948.20071910319</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q1A41976.20071930206">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q1A41976.20071930206</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q1A42033.20071970155">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q1A42033.20071970155</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="QS_Q1B41948.20071910937">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q1B41948.20071910937</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q1B41982.20071931858">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q1B41982.20071931858</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q1B42033.20071971019">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q1B42033.20071971019</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="6">
            <fileIngestible isMetadata="false" name="QS_Q2A41948.20071921253">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2A41948.20071921253</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2A41988.20071941308">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2A41988.20071941308</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2A42033.20071971305">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2A42033.20071971305</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2A41948.20071921253.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2A41948.20071921253.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2A41987.20071941308.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2A41987.20071941308.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2A42033.20071971305.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2A42033.20071971305.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="6">
            <fileIngestible isMetadata="false" name="QS_Q2B41948.20071921305">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2B41948.20071921305</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2B41993.20071951445">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2B41993.20071951445</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2B42033.20071971314">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2B42033.20071971314</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2B41948.20071921315.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2B41948.20071921315.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2B41993.20071951455.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2B41993.20071951455.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_Q2B42033.20071971324.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_Q2B42033.20071971324.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="QS_SATT_20071910313.20071910622">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SATT_20071910313.20071910622</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_SATT_20071931058.20071931341">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SATT_20071931058.20071931341</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_SATT_20071962302.20071970151">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SATT_20071962302.20071970151</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="QS_SCAL41949.20071910936">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SCAL41949.20071910936</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_SCAL42013.20071951746">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SCAL42013.20071951746</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_SCAL42034.20071971017">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SCAL42034.20071971017</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="QS_SEPHG20071910313.20071910622">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SEPHG20071910313.20071910622</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_SEPHG20071940653.20071940951">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SEPHG20071940653.20071940951</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_SEPHG20071962302.20071970151">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SEPHG20071962302.20071970151</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_SPOSTPROD.20071971747">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/QS_SPOSTPROD.20071971747</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="REV_TIME.DAT">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/REV_TIME.DAT</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="2">
            <fileIngestible isMetadata="false" name="SNWP1200719212">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/SNWP1200719212</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="SNWP1200719706">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/SNWP1200719706</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT ANCILLARY">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="SNWP2200719706">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/anc/SNWP2200719706</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 0">
          <version>0</version>
          <files count="6">
            <fileIngestible isMetadata="false" name="QS_S0A20071910154.20071910435">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L0/QS_S0A20071910154.20071910435</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_S0A20071930048.20071930343">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L0/QS_S0A20071930048.20071930343</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_S0A20071970022.20071970343">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L0/QS_S0A20071970022.20071970343</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_S0B20071910154.20071910435">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L0/QS_S0B20071910154.20071910435</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_S0B20071940839.20071941134">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L0/QS_S0B20071940839.20071941134</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_S0B20071970022.20071970343">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L0/QS_S0B20071970022.20071970343</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 1A">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="QS_S1A41948.20071910319">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L1A/QS_S1A41948.20071910319</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_S1A41976.20071930206">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L1A/QS_S1A41976.20071930206</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_S1A42033.20071970155">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L1A/QS_S1A42033.20071970155</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 1B">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S1B41948.20071910937">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L1B/QS_S1B41948.20071910937</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 1B">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S1B41994.20071940959">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L1B/QS_S1B41994.20071940959</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 1B">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S1B42033.20071971019">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L1B/QS_S1B42033.20071971019</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2A">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2A41948.20071921253">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2A/QS_S2A41948.20071921253</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2A COMP 12">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2A41948.20071921253.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2A_12/QS_S2A41948.20071921253.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2A">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2A41967.20071931304">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2A/QS_S2A41967.20071931304</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2A COMP 12">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2A41994.20071951435.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2A_12/QS_S2A41994.20071951435.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2A">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2A42033.20071971305">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2A/QS_S2A42033.20071971305</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2A COMP 12">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2A42033.20071971305.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2A_12/QS_S2A42033.20071971305.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2B">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2B41948.20071921305">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2B/QS_S2B41948.20071921305</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2B">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2B41994.20071951445">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2B/QS_S2B41994.20071951445</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2B">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2B42033.20071971314">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2B/QS_S2B42033.20071971314</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2B COMP 12">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2B41948.20071921315.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2B_12/QS_S2B41948.20071921315.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2B COMP 12">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2B41994.20071951455.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2B_12/QS_S2B41994.20071951455.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 2B COMP 12">
          <version>0</version>
          <files count="1">
            <fileIngestible isMetadata="false" name="QS_S2B42033.20071971324.CP12">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L2B_12/QS_S2B42033.20071971324.CP12</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT LEVEL 3">
          <version>0</version>
          <files count="2">
            <fileIngestible isMetadata="false" name="QS_XWGRD3_2007191.20071971736">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L3/QS_XWGRD3_2007191.20071971736</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="QS_XWGRD3_2007194.20071971737">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/L3/QS_XWGRD3_2007194.20071971737</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT RAW TELEMETRY">
          <version>0</version>
          <files count="2">
            <fileIngestible isMetadata="false" name="qst20070713210940p01hk2.dat">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/raw/qst20070713210940p01hk2.dat</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="qst20070716162150p62hk2.dat">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/raw/qst20070716162150p62hk2.dat</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT RAW TELEMETRY">
          <version>0</version>
          <files count="3">
            <fileIngestible isMetadata="false" name="qst20070712081150p62sci.dat">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/raw/qst20070712081150p62sci.dat</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="qst20070714072020p62sci.dat">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/raw/qst20070714072020p62sci.dat</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="qst20070716162150p62sci.dat">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/raw/qst20070716162150p62sci.dat</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
        <ingestiblePackage category="QSCAT RAW TELEMETRY">
          <version>0</version>
          <files count="2">
            <fileIngestible isMetadata="false" name="qst20070711000747p51hk1.dat">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/raw/qst20070711000747p51hk1.dat</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
            <fileIngestible isMetadata="false" name="qst20070713210940p01hk1.dat">
              <source>
                <link>ftp://seastorm.jpl.nasa.gov/data/dev/ingest-test/oceanids0/raw/qst20070713210940p01hk1.dat</link>
              </source>
              <ingestMode>BINARY</ingestMode>
            </fileIngestible>
          </files>
          <status>READY</status>
        </ingestiblePackage>
      </ingestiblePackages>
      <comment>Submission Package QSCAT Batch 0922 q=nas-archive</comment>
    </ingestMsg>
  </productMsg>
  <origin agent="thuang@spmsubmit" ip="127.0.0.1" time="1196799269735"/>
  <target agent="QSCAT:QSCAT_1" ip="127.0.0.1" time="1196799269896"/>
</message>
