//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.01 at 06:48:17 PM GMT-08:00 
//


package gov.nasa.horizon.archive.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nasa.horizon.archive.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nasa.horizon.archive.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Packet.IdList }
     * 
     */
    public Packet.IdList createPacketIdList() {
        return new Packet.IdList();
    }

    /**
     * Create an instance of {@link Packet.Error }
     * 
     */
    public Packet.Error createPacketError() {
        return new Packet.Error();
    }

    /**
     * Create an instance of {@link Packet.GranuleList }
     * 
     */
    public Packet.GranuleList createPacketGranuleList() {
        return new Packet.GranuleList();
    }

    /**
     * Create an instance of {@link Packet }
     * 
     */
    public Packet createPacket() {
        return new Packet();
    }

    /**
     * Create an instance of {@link Packet.DatasetList }
     * 
     */
    public Packet.DatasetList createPacketDatasetList() {
        return new Packet.DatasetList();
    }

    /**
     * Create an instance of {@link Packet.GranuleReferencetList }
     * 
     */
    public Packet.GranuleReferencetList createPacketGranuleReferencetList() {
        return new Packet.GranuleReferencetList();
    }

}
