//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.01 at 06:48:17 PM GMT-08:00 
//


package gov.nasa.horizon.archive.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="IdList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ids" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DatasetList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="encodedDataset" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GranuleList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="encodedGranule" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GranuleReferencetList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="encodedGranuleRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Error">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *                   &lt;element name="stack_trace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="of" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idList",
    "datasetList",
    "granuleList",
    "granuleReferencetList",
    "error"
})
@XmlRootElement(name = "Packet")
public class Packet {

    @XmlElement(name = "IdList")
    protected Packet.IdList idList;
    @XmlElement(name = "DatasetList")
    protected Packet.DatasetList datasetList;
    @XmlElement(name = "GranuleList")
    protected Packet.GranuleList granuleList;
    @XmlElement(name = "GranuleReferencetList")
    protected Packet.GranuleReferencetList granuleReferencetList;
    @XmlElement(name = "Error")
    protected Packet.Error error;
    @XmlAttribute
    protected Integer page;
    @XmlAttribute
    protected Integer of;

    /**
     * Gets the value of the idList property.
     * 
     * @return
     *     possible object is
     *     {@link Packet.IdList }
     *     
     */
    public Packet.IdList getIdList() {
        return idList;
    }

    /**
     * Sets the value of the idList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packet.IdList }
     *     
     */
    public void setIdList(Packet.IdList value) {
        this.idList = value;
    }

    /**
     * Gets the value of the datasetList property.
     * 
     * @return
     *     possible object is
     *     {@link Packet.DatasetList }
     *     
     */
    public Packet.DatasetList getDatasetList() {
        return datasetList;
    }

    /**
     * Sets the value of the datasetList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packet.DatasetList }
     *     
     */
    public void setDatasetList(Packet.DatasetList value) {
        this.datasetList = value;
    }

    /**
     * Gets the value of the granuleList property.
     * 
     * @return
     *     possible object is
     *     {@link Packet.GranuleList }
     *     
     */
    public Packet.GranuleList getGranuleList() {
        return granuleList;
    }

    /**
     * Sets the value of the granuleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packet.GranuleList }
     *     
     */
    public void setGranuleList(Packet.GranuleList value) {
        this.granuleList = value;
    }

    /**
     * Gets the value of the granuleReferencetList property.
     * 
     * @return
     *     possible object is
     *     {@link Packet.GranuleReferencetList }
     *     
     */
    public Packet.GranuleReferencetList getGranuleReferencetList() {
        return granuleReferencetList;
    }

    /**
     * Sets the value of the granuleReferencetList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packet.GranuleReferencetList }
     *     
     */
    public void setGranuleReferencetList(Packet.GranuleReferencetList value) {
        this.granuleReferencetList = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Packet.Error }
     *     
     */
    public Packet.Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packet.Error }
     *     
     */
    public void setError(Packet.Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPage() {
        if (page == null) {
            return  1;
        } else {
            return page;
        }
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPage(Integer value) {
        this.page = value;
    }

    /**
     * Gets the value of the of property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getOf() {
        if (of == null) {
            return  1;
        } else {
            return of;
        }
    }

    /**
     * Sets the value of the of property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOf(Integer value) {
        this.of = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="encodedDataset" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encodedDataset"
    })
    public static class DatasetList {

        protected List<String> encodedDataset;

        /**
         * Gets the value of the encodedDataset property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the encodedDataset property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEncodedDataset().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEncodedDataset() {
            if (encodedDataset == null) {
                encodedDataset = new ArrayList<String>();
            }
            return this.encodedDataset;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
     *         &lt;element name="stack_trace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "message",
        "stackTrace"
    })
    public static class Error {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String message;
        @XmlElement(name = "stack_trace")
        protected String stackTrace;

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

        /**
         * Gets the value of the stackTrace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStackTrace() {
            return stackTrace;
        }

        /**
         * Sets the value of the stackTrace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStackTrace(String value) {
            this.stackTrace = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="encodedGranule" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encodedGranule"
    })
    public static class GranuleList {

        protected List<String> encodedGranule;

        /**
         * Gets the value of the encodedGranule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the encodedGranule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEncodedGranule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEncodedGranule() {
            if (encodedGranule == null) {
                encodedGranule = new ArrayList<String>();
            }
            return this.encodedGranule;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="encodedGranuleRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encodedGranuleRef"
    })
    public static class GranuleReferencetList {

        protected List<String> encodedGranuleRef;

        /**
         * Gets the value of the encodedGranuleRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the encodedGranuleRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEncodedGranuleRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEncodedGranuleRef() {
            if (encodedGranuleRef == null) {
                encodedGranuleRef = new ArrayList<String>();
            }
            return this.encodedGranuleRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ids" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ids"
    })
    public static class IdList {

        @XmlElement(type = Integer.class)
        protected List<Integer> ids;

        /**
         * Gets the value of the ids property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ids property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIds().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getIds() {
            if (ids == null) {
                ids = new ArrayList<Integer>();
            }
            return this.ids;
        }

    }

}
