CREATE TABLE J1SLX_CATALOGENTRY 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"AUTHOR" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CNES_APPROVAL" NUMBER(1,0) NOT NULL ENABLE, 
	"CYCLE" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL_ID" VARCHAR2(255 CHAR), 
	"GDR_ARCH_TIME" NUMBER(19,0) NOT NULL ENABLE, 
	"GDR_DATE" NUMBER(19,0), 
	"GDRNC_DATE" NUMBER(19,0), 
	"GDRNC_STAGED" NUMBER(1,0) NOT NULL ENABLE, 
	"NASA_APPROVAL" NUMBER(1,0) NOT NULL ENABLE, 
	"PRODUCT_VERSION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SGDR_DATE" NUMBER(19,0), 
	"SGDR_STAGED" NUMBER(1,0) NOT NULL ENABLE, 
	"SGDRNC_DATE" NUMBER(19,0), 
	"SGDRNC_STAGED" NUMBER(1,0) NOT NULL ENABLE, 
	"SSHANC_DATE" NUMBER(19,0), 
	"SSHANC_STAGED" NUMBER(1,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
   );
 
CREATE TABLE J1SLX_CATALOGENTRYGRANULE 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"ENTRY_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"GRANULE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"MOVED" NUMBER(1,0) NOT NULL ENABLE, 
	"OPEN_DATASET" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ORIGINAL_DATASET" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID"),
	 CONSTRAINT "FK2E7F48F64D33345A" FOREIGN KEY ("ENTRY_ID")
	  REFERENCES J1SLX_CATALOGENTRY("ID") ENABLE
   );


  CREATE TABLE J1SLX_SYSTEMMETADATA 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"DATASET_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LAST_RUN_TIME" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
   ) ;

 CREATE SEQUENCE  "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
