//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 10:30:52 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://podaac.nasa.gov/distribute/subscriber/cache")
package gov.nasa.horizon.distribute.subscriber.cache;
